openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://cdc23c9107e6:8080
    description: Generated server url
paths:
  "/api/auth/register":
    post:
      tags:
        - auth-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RegisterRequest"
        required: true
      responses:
        '200':
          description: OK
  "/api/auth/logout":
    post:
      tags:
        - auth-controller
      operationId: logout
      responses:
        '200':
          description: OK
  "/api/auth/login":
    post:
      tags:
        - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LoginRequest"
        required: true
      responses:
        '200':
          description: OK
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
          pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_\-+=\[\]{};':"\\|,.<>/?]).{6,}$
        confirmPassword:
          type: string
          minLength: 1
      required:
        - confirmPassword
        - email
        - password
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
        - email
        - password
