server:
  port: ${API_GATEWAY_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  application:
    name: ${API_GATEWAY_HOST}
  cloud:
    gateway:
      routes:
        - id: docs-auth
          uri: lb://${AUTH_APP_NAME}
          predicates:
            - Path=/${AUTH_APP_NAME}/v3/api-docs
          filters:
            - StripPrefix=1

        - id: auth
          uri: lb://${AUTH_APP_NAME}
          predicates:
            - Path=/api/auth/**

        - id: docs-product
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/${PRODUCT_APP_NAME}/v3/api-docs
          filters:
            - StripPrefix=1

        - id: public-product
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/api/products, /api/products/batch, /api/products/{productId}
            - Method=GET

        - id: admin-product
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/api/products/admin, /api/products/admin/**
          filters:
            - name: JwtAuthentication
              args:
                roles:
                  - ROLE_ADMIN

        - id: admin-images
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/api/products/images
            - Method=POST
          filters:
            - name: JwtAuthentication
              args:
                roles:
                  - ROLE_ADMIN

        - id: product-images
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/images/**
            - Method=GET

        - id: public-category
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/api/categories

        - id: admin-category
          uri: lb://${PRODUCT_APP_NAME}
          predicates:
            - Path=/api/categories/admin/**
          filters:
            - name: JwtAuthentication
              args:
                roles:
                  - ROLE_ADMIN


        - id: docs-cart
          uri: lb://${CART_APP_NAME}
          predicates:
            - Path=/${CART_APP_NAME}/v3/api-docs
          filters:
            - StripPrefix=1

        - id: anonymous-cart
          uri: lb://${CART_APP_NAME}
          predicates:
            - Path=/api/carts/anonymous, /api/carts/anonymous/**

        - id: cart
          uri: lb://${CART_APP_NAME}
          predicates:
            - Path=/api/carts, /api/carts/**
          filters:
            - name: JwtAuthentication
              args:
                roles:
                  - ROLE_USER
                  - ROLE_ADMIN


        - id: docs-order
          uri: lb://${ORDER_APP_NAME}
          predicates:
            - Path=/${ORDER_APP_NAME}/v3/api-docs
          filters:
            - StripPrefix=1

        - id: anonymous-order
          uri: lb://${ORDER_APP_NAME}
          predicates:
            - Path=/api/orders/anonymous

        - id: order
          uri: lb://${ORDER_APP_NAME}
          predicates:
            - Path=/api/orders, /api/orders/**
          filters:
            - name: JwtAuthentication
              args:
                roles:
                  - ROLE_USER
                  - ROLE_ADMIN


springdoc:
  swagger-ui:
    urls:
      - name: ${AUTH_APP_NAME}
        url: /${AUTH_APP_NAME}/v3/api-docs

      - name: ${PRODUCT_APP_NAME}
        url: /${PRODUCT_APP_NAME}/v3/api-docs

      - name: ${CART_APP_NAME}
        url: /${CART_APP_NAME}/v3/api-docs

      - name: ${ORDER_APP_NAME}
        url: /${ORDER_APP_NAME}/v3/api-docs


    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true


application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true