global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api_gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'Api Gateway'
  - job_name: 'auth_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']
        labels:
          application: 'Auth Service'
  - job_name: 'cart_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cart-service:8080']
        labels:
          application: 'Cart Service'
  - job_name: 'eureka_server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']
        labels:
          application: 'Eureka Server'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service'
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: 'Order Service'
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8080']
        labels:
          application: 'Product Service'
  - job_name: 'stock_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['stock-service:8080']
        labels:
          application: 'Stock Service'